# Generated by Django 2.0.2 on 2018-03-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('elementary', '初级'), ('intermediate', '中级'), ('advanced', '高级')], max_length=10, verbose_name='等级'),
        ),
    ]
