# Generated by Django 2.0.2 on 2018-03-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='course/%Y/%m', verbose_name='封面图'),
        ),
    ]
