# Generated by Django 2.0.2 on 2018-03-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20180319_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='before_diving_in',
            field=models.CharField(default='', max_length=400, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_advice',
            field=models.CharField(default='', max_length=400, verbose_name='老师告诉你'),
        ),
    ]
